services:
  proxy:
    depends_on:
      - stac
    build:
      context: examples/opa
    environment:
      UPSTREAM_URL: ${UPSTREAM_URL:-http://stac:8001}
      OIDC_DISCOVERY_URL: ${OIDC_DISCOVERY_URL:-http://localhost:8888/.well-known/openid-configuration}
      OIDC_DISCOVERY_INTERNAL_URL: ${OIDC_DISCOVERY_INTERNAL_URL:-http://oidc:8888/.well-known/openid-configuration}
      ITEMS_FILTER_CLS: opa_integration:OpaIntegration
      ITEMS_FILTER_ARGS: "[]"
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
