issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: stac
    redirectURIs:
      - "http://localhost:8000/docs/oauth2-redirect"
    name: "STAC API (behind auth proxy)"
    secret: super-super-secret

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    username: "admin"
    # password: "password"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
