"$schema": "https://json-schema.org/draft-07/schema#"
type: object
properties:
  replicaCount:
    type: integer
    minimum: 1
    description: "Number of replicas for the deployment"

  image:
    type: object
    properties:
      repository:
        type: string
        description: "Docker image repository"
        default: "ghcr.io/developmentseed/stac-auth-proxy"
      pullPolicy:
        type: string
        enum: ["IfNotPresent", "Always", "Never"]
        description: "Kubernetes image pull policy"
      tag:
        type: string
        description: "Docker image tag"
        default: "latest"

  service:
    type: object
    required: ["type", "port"]
    properties:
      type:
        type: string
        enum: ["ClusterIP", "NodePort", "LoadBalancer"]
        description: "Kubernetes service type"
      port:
        type: integer
        minimum: 1
        maximum: 65535
        description: "Service port number"

  ingress:
    type: object
    properties:
      enabled:
        type: boolean
        description: "Enable ingress resource"
      className:
        type: string
        description: "Ingress class name (e.g., nginx)"
      annotations:
        type: object
        additionalProperties:
          type: string
        description: "Annotations for the ingress resource"
      host:
        type: string
        description: "Hostname for the ingress"
      tls:
        type: object
        properties:
          enabled:
            type: boolean
            description: "Enable TLS configuration"
          secretName:
            type: string
            description: "Name of the TLS secret (optional, will be auto-generated if empty)"
        required: ["enabled"]

  resources:
    type: object
    properties:
      limits:
        type: object
        properties:
          cpu:
            type: string
            pattern: "^[0-9]+m?$|^[0-9]+\\.[0-9]+$"
            description: "CPU limit (e.g., 500m, 1.5)"
          memory:
            type: string
            pattern: "^[0-9]+(Ki|Mi|Gi|Ti|Pi|Ei|[kMGTPE]i?)?$"
            description: "Memory limit (e.g., 512Mi, 1Gi)"
      requests:
        type: object
        properties:
          cpu:
            type: string
            pattern: "^[0-9]+m?$|^[0-9]+\\.[0-9]+$"
            description: "CPU request (e.g., 200m, 0.5)"
          memory:
            type: string
            pattern: "^[0-9]+(Ki|Mi|Gi|Ti|Pi|Ei|[kMGTPE]i?)?$"
            description: "Memory request (e.g., 256Mi, 1Gi)"

  securityContext:
    type: object
    properties:
      runAsNonRoot:
        type: boolean
        description: "Requires the container to run without root privileges"
      runAsUser:
        type: integer
        description: "The UID to run the entrypoint of the container process"
      runAsGroup:
        type: integer
        description: "The GID to run the entrypoint of the container process"
    description: "Pod-level security context"

  containerSecurityContext:
    type: object
    properties:
      allowPrivilegeEscalation:
        type: boolean
        description: "Controls whether a process can gain more privileges than its parent process"
      capabilities:
        type: object
        properties:
          drop:
            type: array
            items:
              type: string
            description: "List of capabilities to drop"
    description: "Container-level security context"

  nodeSelector:
    type: object
    additionalProperties:
      type: string
    description: "Node labels for pod assignment"

  tolerations:
    type: array
    items:
      type: object
      properties:
        key:
          type: string
        operator:
          type: string
          enum: ["Exists", "Equal"]
        value:
          type: string
        effect:
          type: string
          enum: ["NoSchedule", "PreferNoSchedule", "NoExecute"]
    description: "Pod tolerations"

  affinity:
    type: object
    additionalProperties: true
    description: "Pod affinity rules"

  env:
    type: object
    required: ["UPSTREAM_URL", "OIDC_DISCOVERY_URL"]
    properties:
      UPSTREAM_URL:
        type: string
        format: uri
        description: "STAC API URL"
      OIDC_DISCOVERY_URL:
        type: string
        format: uri
        description: "OpenID Connect discovery document URL"
      OIDC_DISCOVERY_INTERNAL_URL:
        type: string
        format: uri
        description: "Internal network OpenID Connect discovery document URL"
      WAIT_FOR_UPSTREAM:
        type: boolean
        description: "Wait for upstream API to become available"
        default: true
      HEALTHZ_PREFIX:
        type: string
        description: "Path prefix for health check endpoints"
        default: "/healthz"
      DEFAULT_PUBLIC:
        type: boolean
        description: "Default access policy for endpoints"
        default: false
      PRIVATE_ENDPOINTS:
        type: string
        description: "JSON string of endpoints requiring authentication"
      PUBLIC_ENDPOINTS:
        type: string
        description: "JSON string of public endpoints when DEFAULT_PUBLIC is false"
      OPENAPI_SPEC_ENDPOINT:
        type: ["string", "null"]
        description: "Path of OpenAPI specification"
      ITEMS_FILTER_CLS:
        type: ["string", "null"]
        description: "CQL2 expression generator class"
      ITEMS_FILTER_ARGS:
        type: string
        description: "JSON string of positional arguments for filter class"
        default: "[]"
      ITEMS_FILTER_KWARGS:
        type: string
        description: "JSON string of keyword arguments for filter class"
        default: "{}"


  serviceAccount:
    type: object
    properties:
      create:
        type: boolean
        description: "Specifies whether a service account should be created"
      annotations:
        type: object
        additionalProperties:
          type: string
        description: "Annotations to add to the service account"
      name:
        type: string
        description: "The name of the service account to use. If not set and create is true, a name is generated"
      imagePullSecrets:
        type: array
        description: "Image pull secrets to add to the service account"
        items:
          type: object
          required: ["name"]
          properties:
            name:
              type: string
              description: "Name of the image pull secret"

required:
  - service 