name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/publish-helm.yaml'
  release:
    types: [created]

jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        run: |
          VERSION_ARGS=""
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
            VERSION_ARGS="--version $VERSION --app-version $VERSION"
          fi
          helm package helm/ $VERSION_ARGS

      - name: Push Helm Chart
        run: |
          helm push *.tgz oci://ghcr.io/${{ github.repository }}/charts 